== Adding Shadow

.application/build.gradle
[source,gradle]
----
include::code/application/build.gradle[tags=apply]
----

== !

[source,bash]
----
$ gradle application:shadowJar && \
  java -jar application/build/libs/application-shadow.jar
Client Version 1.0.0
----

== Configuring the task

.application/build.gradle
[source,gradle]
----
include::code/application/build.gradle[tags=config]
----
<1> Change the default of `all`

== Integration with Application

.application/build.gradle
[source,gradle]
----
include::code/application/build.gradle[tags=application]
----

== !

[source,bash]
----
$ gradle runShadow
$ gradle distShadowTar
$ gradle distShadowZip
----

== Filtering Files

Use the standard methods from `Jar` task

== !

.application-resolved-versions/build.gradle
[source,gradle]
----
include::code/application-resolved-versions/build.gradle[tags=excludeFile]
----


== !

[source,bash]
----
$ gradle application-resolved-versions:jarContent
META-INF/
META-INF/MANIFEST.MF
shadow/
shadow/App.class
shadow/AdapterVersion.class
META-INF/services/
META-INF/services/shadow.client.Version
shadow/client/
shadow/client/Version.class
shadow/Version.class
----

== Filtering Dependencies

Use the `dependencies{}` block

== !

.application-filter-dependency/build.gradle
[source,gradle]
----
include::code/application-filter-dependency/build.gradle[tags=excludeDep]
----

== !

[source,bash]
----
$ gradle :application-filter-dependency:jarContent
META-INF/
META-INF/MANIFEST.MF
shadow/
shadow/AdapterVersion.class
adapter.properties
META-INF/services/
META-INF/services/shadow.client.Version
----

== !

* Dependency Filters are explicit per dependency
* This means, you **must** exclude transitive deps explicitly

== Shadow Configuration

`project.configurations.shadow` holds runtime dependencies that are **not** merged

== !

.application-shadow-conf/build.gradle
[source,gradle]
----
include::code/application-shadow-conf/build.gradle[tags=dependencies]
----
<1> This library will not be merged into the JAR

== !

.application-shadow-conf/build.gradle
[source,gradle]
----
include::code/application-shadow-conf/build.gradle[tags=classpath]
----
<1> `configurations.shadow` is not added to the compile classpath by default

== !

[source,bash]
----
$ gradle :application-shadow-conf:jarContent \
    :application-shadow-conf:runShadow
META-INF/
META-INF/MANIFEST.MF
shadow/
shadow/App.class
shadow/AdapterVersion.class
adapter.properties
META-INF/services/
META-INF/services/shadow.client.Version
shadow/client/
shadow/client/Version.class
shadow/Version.class

Adapter: Client Version 2.0.0
Executing runtime code!
----

== JAR Transformations

== Service Descriptors

.application-transformer/build.gradle
[source,gradle]
----
include::code/application-transformer/build.gradle[tags=mergeService]
----

== !

[source,bash]
----
$ gradle application-transformer:showServices
1.0.0
1.0.0-additional
----

== Other transforms

.application-transformer/build.gradle
[source,gradle]
----
include::code/application-transformer/build.gradle[tags=transforms]
----

== Package Relocation

[.center]
== Conflicting dependencies

[graphviz.center, dot-example, svg]
----
digraph g {
    clienta[label="client:v1.0.0"]
    clientb[label="client:v2.0.0"]
    adapter[label="adapter:v1.0.0"]
    adapter -> clientb
    application -> adapter
    application -> clienta
    rankdir=BT
    {rank=same;clienta,clientb}
}
----

== !

.application-resolved-versions/build.gradle
[source,gradle]
----
include::code/application-resolved-versions/build.gradle[tags=dependencies]
----

== !

.application-resolved-versions/src/main/java/shadow/App.java
[source,java]
----
include::code/application-resolved-versions/src/main/java/shadow/App.java[tags=main]
----

== !
[source,bash]
----
$ gradle application-resolved-versions:runShadow
Adapter: Client Version 2.0.0
Client Version 2.0.0
----

== Relocate

.client-adapter/build.gradle
[source,gradle]
----
include::code/client-adapter/build.gradle[tags=relocate]
----

== Update Dependency

.application-adapter-all/build.gradle
[source,gradle]
----
include::code/application-adapter-all/build.gradle[tags=dependencies]
----

== !

[source,bash]
----
$ gradle application-adapter-all:runShadow
Adapter: Client Version 2.0.0
Client Version 1.0.0
----

== Publishing Shadow JARs

Simply apply Maven or Maven-Publish

(ivy-publishing untested)

== With Maven-Publish Plugin

.client-adapter-maven-publish/build.gradle
[source,gradle]
----
include::code/client-adapter-maven-publish/build.gradle[tags=publish]
----

== !

[source,bash]
----
$ gradle :client-adapter-maven-publish:publishToMavenLocal
$ ls ~/.m2/repositories/shadow/client-adapter-maven-publish/1.0.0/
client-adapter-maven-publish-1.0.0-all.jar <1>
client-adapter-maven-publish-1.0.0.pom
----
<1> Notice the use of an artifact classifier

== Producing a Top Level Artifact w/ Shadow

== With Maven-Publish Plugin

== First, Configure ShadowJar

.client-adapter-relocate/build.gradle
[source,gradle]
----
include::code/client-adapter-relocate/build.gradle[tags=rename]
----
<1> Override the baseName to not step on JAR output
<2> Remove the classifier as this will be a root artifact


== Then Configure Publishing

.client-adapter-relocate/build.gradle
[source,gradle]
----
include::code/client-adapter-relocate/build.gradle[tags=publish]
----

== !

[source,bash]
----
$ gradle :client-adapter-relocate:publishToMavenLocal
$ ls ~/.m2/repositories/shadow/client-adapter-relocate-all/1.0.0/
client-adapter-relocate-all-1.0.0.jar
client-adapter-relocate-all-1.0.0.pom
----

== With Maven Plugin

.client-adapter/build.gradle
[source,gradle]
----
include::code/client-adapter/build.gradle[tags=toplevel]
----

== Multi-Projects

Use the `Map` notation for a project dependency

== !

.multi-app/build.gradle
[source,gradle]
----
include::code/multi-app/build.gradle[tags=dependencies]
----
<1> Depend on the `shadow` configuration from the project

== !

[source,bash]
----
$ gradle :multi-app:run
Adapter: Client Version 2.0.0
Client Version 1.0.0
----
